.build_template_: &build_template
  stage: build
  script:
    - set -eu
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y upgrade
    - cat "${CI_JOB_NAME}.deps" | xargs apt-get -y install
    - sh build.sh "${CI_JOB_NAME%%-*}" "${CI_PROJECT_DIR}/lxd-${CI_JOB_NAME}.tar.gz"
  artifacts:
    untracked: true


#
4.2-buster:
  <<: *build_template
  image: debian:buster
  before_script:
    - export PATH="/usr/lib/go-1.13/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.2-sid:
  <<: *build_template
  image: debian:sid


#
4.3-buster:
  <<: *build_template
  image: debian:buster
  before_script:
    - export PATH="/usr/lib/go-1.13/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.3-kali:
  <<: *build_template
  image: kalilinux/kali-rolling

4.3-sid:
  <<: *build_template
  image: debian:sid


#
4.4-buster:
  <<: *build_template
  image: debian:buster
  before_script:
    - export PATH="/usr/lib/go-1.13/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.4-kali:
  <<: *build_template
  image: kalilinux/kali-rolling

4.4-sid:
  <<: *build_template
  image: debian:sid


#
4.6-sid:
  <<: *build_template
  image: debian:sid


#
4.7-sid:
  <<: *build_template
  image: debian:sid


#
4.8-buster:
  <<: *build_template
  image: debian:buster
  before_script:
    - export PATH="/usr/lib/go-1.13/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.8-sid:
  <<: *build_template
  image: debian:sid


#
4.9-buster:
  <<: *build_template
  image: debian:buster
  before_script:
    - export PATH="/usr/lib/go-1.13/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.9-sid:
  <<: *build_template
  image: debian:sid


#
4.13-buster:
  <<: *build_template
  image: debian:buster
  before_script:
    - export PATH="/usr/lib/go-1.13/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.13-sid:
  <<: *build_template
  image: debian:sid

#
4.17-bullseye:
  <<: *build_template
  image: debian:bullseye
  before_script:
    - export PATH="/usr/lib/go-1.15/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.17-buster:
  <<: *build_template
  image: debian:buster
  before_script:
    - export PATH="/usr/lib/go-1.15/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.17-sid:
  <<: *build_template
  image: debian:sid

4.19-sid:
  <<: *build_template
  image: debian:sid
