.build_template_: &build_template
  stage: build
  script:
    - set -eu
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y upgrade
    - cat "${CI_JOB_NAME}.deps" | xargs apt-get -y install
    - sh build.sh "${CI_JOB_NAME%%-*}" "${CI_PROJECT_DIR}/lxd-${CI_JOB_NAME}.tar.gz"
  artifacts:
    untracked: true


#
4.20-bullseye:
  <<: *build_template
  image: debian:bullseye
  before_script:
    - export PATH="/usr/lib/go-1.17/bin:$PATH"
    - echo deb http://deb.debian.org/debian "${CI_JOB_NAME##*-}-backports" main >/etc/apt/sources.list.d/backports.list

4.20-sid:
  <<: *build_template
  image: debian:sid
